language: python

python:
  - 3.6

env:
  - PIPENV_SHELL_COMPAT=true PIPENV_COLORBLIND=true PIPENV_NOSPIN=true

install:
  - pip install pipenv
  - pipenv install --system --deploy -d

script:
  - pipenv run python -m pytest

notifications:
  email:
    on_success: never
    on_failure: change
